apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: k8s-simple-web
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: k8s-simple-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: k8s-simple-web
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: k8s-simple-web
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db
